### ISSUE TITLE
和minio对比

### ISSUE THREAD

**Issue by timchenxiaoyu** [donnie4w/wfs#1]
请问你这个和minio的区别和优缺点？

**Comment by wangwei123** [comment]
我用了minio，各方面都还不错，就是文件访问链接7天就过期了，目前这个视乎不错，就是没有Bucket的概念和后台管理

**Comment by wangwei123** [comment]
我用了minio，各方面都还不错，就是文件访问链接7天就过期了，目前这个wfs视乎不错，就是没有Bucket的概念和后台管理

**Comment by ledao** [comment]
minio挺好的，生产用过一段时间总结下：
1. 安全工单有点多（但也说明维护好）；
2. minio是强时间一致性，每次重启集群总会有失败的情况，要多重启几次（但也说明他们宣传的严肃的高稳定性）；
3. 扩容、修改server是真的麻烦……

今天刚看到wfs，没见到分布式部署的文档，希望谁知道在哪里，麻烦贴下哈。

**Comment by donnie4w** [comment]
你好！
wfs目前的版本只是单机实现，本身没有实现分布式。可能以后会实现，不过现阶段只能单机部署。在官网上说的分布式部署建议，本质上是一种负载均衡策略；
利用 文件路径 进行路由分发。可以参见这篇文章： https://tlnet.top/article/22425158 
谢谢你对minio总结分享，你说的问题，也是wfs去掉 0.x版本的分布式实现的原因之一，实践中，分布式的确有众多问题，要完善它，是一个复杂的过程，否则，分布式的作用可能适得其反。
wfs的负载均衡可以解决在线动态扩容的问题，但是文件的数据备份需要手动完成。
donnie
***@***.***
---- 回复的原邮件 ----
***@***.***>发送日期2024年3月15日 ***@***.***>***@***.***>主题Re: [donnie4w/wfs] 和minio对比 (#1)
minio挺好的，生产用过一段时间总结下：
安全工单有点多（但也说明维护好）；
minio是强时间一致性，每次重启集群总会有失败的情况，要多重启几次（但也说明他们宣传的严肃的高稳定性）；
扩容、修改server是真的麻烦……
今天刚看到wfs，没见到分布式部署的文档，希望谁知道在哪里，麻烦贴下哈。

**Comment by ledao** [comment]
感谢解答
