### ISSUE TITLE
可以查询目前已上传的文件名称吗？

### ISSUE THREAD

**Issue by zhaoxiong123** [donnie4w/wfs#2]
可以查询目前已上传的文件名称吗？

**Comment by donnie4w** [comment]
可以通过管理后台查询
[官网](https://tlnet.top/wfs)

**Comment by MrLuan** [comment]
> 可以通过管理后台查询 [官网](https://tlnet.top/wfs)

大神能不能优化一下客户端接口啊, 增加一个可以快速获取文件名列表的接口啊, 我的应用要有批量删除文件的功能, 能不能删除文件哪里支持通配符 ( * )
